CREATE TABLE IF NOT EXISTS `#__multicache_advanced_ccomp_factor_base` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `loadinstruc_state` varchar(255) NOT NULL,
  `avg_load_time` int(11) NOT NULL,
  `var_load_time` int(11) NOT NULL,
  `ccomp_factor` float NOT NULL,
  `loadtime_score` int(11) NOT NULL,
  `loadvar_score` float NOT NULL,
  `statmode` int(11) NOT NULL,
  `statmode_score` int(11) NOT NULL,
  `total_score` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `#__multicache_advanced_loadinstruction_base` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `loadinstruc_state` varchar(255) NOT NULL,
  `avg_load_time` int(11) NOT NULL,
  `var_load_time` int(11) NOT NULL,
  `precache_factor` int(11) NOT NULL,
  `loadtime_score` int(11) NOT NULL,
  `loadvar_score` float NOT NULL,
  `statmode` int(11) NOT NULL,
  `statmode_score` int(11) NOT NULL,
  `total_score` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `#__multicache_advanced_precache_factor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `loadinstruc_state` varchar(255) NOT NULL,
  `avg_load_time` int(11) NOT NULL,
  `var_load_time` int(11) NOT NULL,
  `precache_factor` int(11) NOT NULL,
  `loadtime_score` int(11) NOT NULL,
  `loadvar_score` float NOT NULL,
  `statmode` int(11) NOT NULL,
  `statmode_score` int(11) NOT NULL,
  `total_score` float NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `#__multicache_advanced_testgroups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `test_page` varchar(255) NOT NULL,
  `cycles` int(11) NOT NULL,
  `cycles_complete` int(11) NOT NULL,
  `expected_tests` int(11) NOT NULL,
  `advanced` varchar(255) NOT NULL,
  `start_date` varchar(255) NOT NULL,
  `end_date` varchar(255) NOT NULL,
  `start_time` varchar(255) NOT NULL,
  `end_time` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `best_load_time` varchar(255) NOT NULL,
  `blt_precache_factor` int(11) NOT NULL,
  `blt_cache_compression_factor` float NOT NULL,
  `blt_loadinstruc_state` varchar(255) NOT NULL,
  `avg_load_time` varchar(255) NOT NULL,
  `variance_on_load_time` varchar(255) NOT NULL,
  `algorithm_precache_factor` int(11) NOT NULL,
  `algorithm_cache_compression_factor` float NOT NULL,
  `algorithm_loadinstruc_state` varchar(255) NOT NULL,
  `pf_assoc_alt` int(11) NOT NULL,
  `pf_assoc_var` int(11) NOT NULL,
  `ccf_assoc_alt` int(11) NOT NULL,
  `ccf_assoc_var` int(11) NOT NULL,
  `loadinstruc_assoc_alt` varchar(255) NOT NULL,
  `loadinstruc_assoc_var` varchar(255) NOT NULL,
  `loaded_precache_factor` int(11) NOT NULL,
  `loaded_cache_compression_factor` float NOT NULL,
  `loaded_loadinstruc_state` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;




CREATE TABLE IF NOT EXISTS `#__multicache_advanced_test_results` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `group_id` int(11) NOT NULL,
  `date_of_test` varchar(255) NOT NULL,
  `mtime` double NOT NULL,
  `max_tests` int(11) NOT NULL,
  `current_test` int(11) NOT NULL,
  `loadinstruc_key` int(11) NOT NULL,
  `loadinstruc_state` varchar(255) NOT NULL,
  `precache_factor` int(11) NOT NULL,
  `cache_compression_factor` float NOT NULL,
  `page_load_time` int(11) NOT NULL,
  `html_bytes` int(11) NOT NULL,
  `page_elements` int(11) NOT NULL,
  `report_url` varchar(255) NOT NULL,
  `html_load_time` int(11) NOT NULL,
  `page_bytes` int(11) NOT NULL,
  `pagespeed_score` int(11) NOT NULL,
  `yslow_score` int(11) NOT NULL,
  `test_id` varchar(255) NOT NULL,
  `test_page` varchar(255) NOT NULL,
  `status` varchar(255) NOT NULL,
  `simulation` varchar(255) NOT NULL,
  `advanced` varchar(255) NOT NULL,
  `test_date` datetime NOT NULL,
  `cache_handler` varchar(255) NOT NULL,
  `hammer_mode` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `gzip_factor` (`cache_compression_factor`),
  KEY `simulation` (`simulation`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;



CREATE TABLE IF NOT EXISTS `#__multicache_config` (
  `id` int(11) NOT NULL,
  `caching` int(11) NOT NULL,
  `cache_handler` varchar(255) NOT NULL,
  `cachetime` int(11) NOT NULL,
  `multicache_persist` int(11) NOT NULL,
  `multicache_compress` int(11) NOT NULL,
  `multicache_server_host` varchar(255) NOT NULL,
  `multicache_server_port` varchar(255) NOT NULL,
  `created` date NOT NULL,
  `gtmetrix_testing` tinyint(2) NOT NULL,
  `gtmetrix_api_budget` int(11) NOT NULL,
  `gtmetrix_email` varchar(255) NOT NULL,
  `gtmetrix_token` varchar(255) NOT NULL,
  `gtmetrix_adblock` tinyint(2) NOT NULL,
  `gtmetrix_test_url` varchar(255) NOT NULL,
  `gtmetrix_allow_simulation` int(11) NOT NULL,
  `simulation_advanced` int(11) NOT NULL,
  `jssimulation_parse` int(11) NOT NULL,
  `gtmetrix_cycles` int(11) NOT NULL,
  `precache_factor_min` int(1) NOT NULL,
  `precache_factor_max` int(1) NOT NULL,
  `precache_factor_default` int(1) NOT NULL,
  `gzip_factor_min` float NOT NULL,
  `gzip_factor_max` float NOT NULL,
  `gzip_factor_step` float NOT NULL,
  `gzip_factor_default` float NOT NULL,
  `googleclientid` varchar(255) NOT NULL,
  `googleclientsecret` varchar(255) NOT NULL,
  `googleviewid` varchar(255) NOT NULL,
  `googlestartdate` varchar(255) NOT NULL,
  `googleenddate` varchar(255) NOT NULL,
  `googlenumberurlscache` int(11) NOT NULL,
  `multicachedistribution` int(11) NOT NULL,
  `additionalpagecacheurls` mediumtext NOT NULL,
  `force_locking_off` int(11) NOT NULL,
  `indexhack` int(11) NOT NULL,
  `conduit_switch` int(11) NOT NULL,
   `minify_html` int(11) NOT NULL,
  `targetpageloadtime` int(11) NOT NULL,
  `algorithmavgloadtimeweight` float NOT NULL,
  `algorithmmodemaxbelowtimeweight` float NOT NULL,
  `algorithmvarianceweight` float NOT NULL,
  `urlfilters` int(11) NOT NULL,
  `frequency_distribution` int(11) NOT NULL,
  `natlogdist` int(11) NOT NULL,
  `deployment_method` int(11) NOT NULL,
  `cartsessionvariables` mediumtext NOT NULL,
  `cartdifferentiators` mediumtext NOT NULL,
  `cartmode` int(11) NOT NULL,
  `cartmodeurlinclude` mediumtext NOT NULL,
  `js_switch` int(11) NOT NULL,
  `default_scrape_url` varchar(255) NOT NULL,
  `social_script_identifiers` mediumtext NOT NULL,
  `advertisement_script_identifiers` mediumtext NOT NULL,
  `pre_head_stub_identifiers` mediumtext NOT NULL,
  `head_stub_identifiers` mediumtext NOT NULL,
  `body_stub_identifiers` mediumtext NOT NULL,
  `footer_stub_identifiers` mediumtext NOT NULL,
  `principle_jquery_scope` int(11) NOT NULL,
  `principle_jquery_scope_other` varchar(255) NOT NULL,
  `dedupe_scripts` int(11) NOT NULL,
  `defer_social` int(11) NOT NULL,
  `defer_advertisement` int(11) NOT NULL,
  `defer_async` int(11) NOT NULL,
  `maintain_preceedence` int(11) NOT NULL,
  `minimize_roundtrips` int(11) NOT NULL,
  `js_comments` int(11) NOT NULL,
  `compress_js` int(11) NOT NULL,
  `debug_mode` int(11) NOT NULL,
  `advanced_simulation_lock` int(11) NOT NULL,
  `js_tweaker_url_include_exclude` int(11) NOT NULL,
  `jst_urlinclude` mediumtext NOT NULL,
  `jst_query_include_exclude` int(11) NOT NULL,
  `jst_query_param` mediumtext NOT NULL,
  `orphaned_scripts` int(11) NOT NULL,
  `excluded_components` mediumtext NOT NULL,
  `jst_url_string` mediumtext NOT NULL,
  `force_precache_off` int(11) NOT NULL,
  `css_switch` int(11) NOT NULL,
  `css_scrape_url` varchar(255) NOT NULL,
  `dedupe_css_styles` int(11) NOT NULL,
  `css_maintain_preceedence` int(11) NOT NULL,
  `group_css_styles` int(11) NOT NULL,
  `compress_css` int(11) NOT NULL,
  `css_special_identifiers` mediumtext NOT NULL,
  `css_comments` int(11) NOT NULL,
  `orphaned_styles_loading` int(11) NOT NULL,
  `css_tweaker_url_include_exclude` int(11) NOT NULL,
  `css_urlinclude` mediumtext NOT NULL,
  `css_query_include_exclude` int(11) NOT NULL,
  `css_query_param` mediumtext NOT NULL,
  `cssexcluded_components` mediumtext NOT NULL,
  `css_url_string` mediumtext NOT NULL,
  `image_lazy_switch` int(11) NOT NULL,
  `image_lazy_container_switch` int(11) NOT NULL,
  `image_lazy_container_strings` mediumtext NOT NULL,
  `image_lazy_image_selector_include_switch` int(11) NOT NULL,
  `image_lazy_image_selector_include_strings` mediumtext NOT NULL,
  `image_lazy_image_selector_exclude_switch` int(11) NOT NULL,
  `image_lazy_image_selector_exclude_strings` mediumtext NOT NULL,
  `imagestweaker_url_include_exclude` int(11) NOT NULL,
  `images_urlinclude` mediumtext NOT NULL,  
  `images_query_include_exclude` int(11) NOT NULL,  
  `images_query_param` mediumtext NOT NULL,
  `images_url_string` mediumtext NOT NULL,
  `imgexcluded_components` mediumtext NOT NULL,
  `params` mediumtext NOT NULL,
  
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `#__multicache_items` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemnumber` int(11) NOT NULL,
  `numberofelements` int(11) NOT NULL,
  `age` int(11) NOT NULL,
  `evicted` int(11) NOT NULL,
  `evicted_nonzero` int(11) NOT NULL,
  `evicted_time` int(11) NOT NULL,
  `outofmemory` int(11) NOT NULL,
  `tailrepairs` int(11) NOT NULL,
  `reclaimed` int(11) NOT NULL,
  `expired_unfetched` int(11) NOT NULL,
  `evicted_unfetched` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `mstimestamp` varchar(255) NOT NULL,
  `nowtimestamp` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


CREATE TABLE IF NOT EXISTS `#__multicache_itemscache` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemnumber` int(11) NOT NULL,
  `item` varchar(255) NOT NULL,
  `size` int(11) NOT NULL,
  `expiration` varchar(255) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `mstimestamp` varchar(255) NOT NULL,
  `nowtimestamp` date NOT NULL,
  `sitehash` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `mgroup` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `#__multicache_items_slabs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `slab_id` int(11) NOT NULL,
  `chunk_size` int(11) NOT NULL,
  `chunks_per_page` int(11) NOT NULL,
  `total_pages` int(11) NOT NULL,
  `total_chunks` int(11) NOT NULL,
  `used_chunks` int(11) NOT NULL,
  `free_chunks` int(11) NOT NULL,
  `free_chunks_end` int(11) NOT NULL,
  `mem_requested` varchar(255) NOT NULL,
  `get_hits` varchar(255) NOT NULL,
  `cmd_set` varchar(255) NOT NULL,
  `delete_hits` varchar(255) NOT NULL,
  `incr_hits` varchar(255) NOT NULL,
  `decr_hits` varchar(255) NOT NULL,
  `cas_hits` varchar(255) NOT NULL,
  `cas_badval` varchar(255) NOT NULL,
  `touch_hits` varchar(255) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `#__multicache_items_stats` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pid` int(11) NOT NULL,
  `uptime` varchar(255) NOT NULL,
  `time` varchar(255) NOT NULL,
  `version` varchar(255) NOT NULL,
  `libevent` varchar(255) NOT NULL,
  `pointer_size` int(11) NOT NULL,
  `rusage_user` float NOT NULL,
  `rusage_system` float NOT NULL,
  `curr_connections` int(11) NOT NULL,
  `total_connections` int(11) NOT NULL,
  `connection_structures` int(11) NOT NULL,
  `reserved_fds` int(11) NOT NULL,
  `cmd_get` int(11) NOT NULL,
  `cmd_set` int(11) NOT NULL,
  `cmd_flush` int(11) NOT NULL,
  `cmd_touch` int(11) NOT NULL,
  `get_hits` int(11) NOT NULL,
  `get_misses` int(11) NOT NULL,
  `delete_hits` int(11) NOT NULL,
  `delete_misses` int(11) NOT NULL,
  `incr_hits` int(11) NOT NULL,
  `incr_misses` int(11) NOT NULL,
  `decr_hits` int(11) NOT NULL,
  `decr_misses` int(11) NOT NULL,
  `cas_hits` int(11) NOT NULL,
  `cas_misses` int(11) NOT NULL,
  `cas_badval` int(11) NOT NULL,
  `touch_hits` int(11) NOT NULL,
  `touch_misses` int(11) NOT NULL,
  `auth_cmds` int(11) NOT NULL,
  `auth_errors` int(11) NOT NULL,
  `bytes_read` int(11) NOT NULL,
  `bytes_written` int(11) NOT NULL,
  `limit_maxbytes` int(22) NOT NULL,
  `accepting_conns` int(11) NOT NULL,
  `listen_disabled_num` int(11) NOT NULL,
  `threads` int(11) NOT NULL,
  `conn_yields` int(11) NOT NULL,
  `hash_power_level` int(11) NOT NULL,
  `hash_bytes` int(11) NOT NULL,
  `hash_is_expanding` int(11) NOT NULL,
  `bytes` int(11) NOT NULL,
  `curr_items` int(11) NOT NULL,
  `total_items` int(11) NOT NULL,
  `expired_unfetched` int(11) NOT NULL,
  `evicted_unfetched` int(11) NOT NULL,
  `evictions` int(11) NOT NULL,
  `reclaimed` int(11) NOT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;


CREATE TABLE IF NOT EXISTS `#__multicache_urlarray` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL,
  `url_manifest` varchar(255) NOT NULL,
  `cache_id` varchar(255) NOT NULL,
  `cache_id_alt` varchar(255) NOT NULL,
  `cache_id_alt_ext` varchar(255) NOT NULL,
  `views` int(11) NOT NULL,
  `f_dist` double NOT NULL,
  `ln_dist` float NOT NULL,
  `type` varchar(255) NOT NULL,
  `created` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

